const FEE_TYPE_MAKER = 'maker'
const FEE_TYPE_TAKER = 'taker'
const FEE_TYPE_FIFTY_FIFTY = 'fifty-fifty'

const FEE_MAKER = -0.025
const FEE_TAKER = 0.075
const FEE_FIFTY_FIFTY = 0.05

const LIMIT_FEES = -0.00025
const MARKET_FEES = 0.00075

const FEES = {
    [FEE_TYPE_MAKER]: FEE_MAKER,
    [FEE_TYPE_TAKER]: FEE_TAKER,
    [FEE_TYPE_FIFTY_FIFTY]: FEE_FIFTY_FIFTY
}

const BITMEX_FEE_CUTOFF = 0.005

const CANDLE_TIME_FRAME_POSITION = 0
const CANDLE_OPEN_POSITION = 1
const CANDLE_HIGH_POSITION = 2
const CANDLE_LOW_POSITION = 3
const CANDLE_CLOSE_POSITION = 4
const CANDLE_VOLUME_POSITION = 5

const CANDLE_POSITIONS = {
    TIME_FRAME: CANDLE_TIME_FRAME_POSITION,
    OPEN: CANDLE_OPEN_POSITION,
    HIGH: CANDLE_HIGH_POSITION,
    LOW: CANDLE_LOW_POSITION,
    CLOSE: CANDLE_CLOSE_POSITION,
    VOLUME: CANDLE_VOLUME_POSITION
}

const BINANCE_EXCHANGE = 'binance'
const BITMEX_EXCHANGE = 'bitmex'

const ALLOWED_EXCHANGES = [BITMEX_EXCHANGE, BINANCE_EXCHANGE]

const ALLOWED_TIME_FRAMES = [
    '1m',
    '5m',
    '15m',
    '30m',
    '1h',
    '4h',
    '6h',
    '12h',
    '1d',
    '1w',
    '1M'
]

const POSITION_LONG = 'long'
const POSITION_SHORT = 'short'

const ORDER_TYPE_MARKET = 'market'
const ORDER_TYPE_LIMIT = 'limit'

const MARGIN_TYPE_ISOLATED = 'ISOLATED'
const MARGIN_TYPE_CROSS = 'CROSS'

const ALLOWED_MARGIN_TYPES = [MARGIN_TYPE_CROSS, MARGIN_TYPE_ISOLATED]

const BUY = 'buy'
const SELL = 'sell'

const BTC = 'BTC'

const ALLOWED_ACCOUNT_TYPES = [POSITION_SHORT, POSITION_LONG]

const DEFAULT_MARKET_THRESHOLD = 10 // USD

const BITMEX_SYMBOLS = ['BTC/USD', 'ETH/USD']
const OTHER_SYMBOLS = ['BTC/USDT', 'ETH/USDT']

const MAP_WS_PAIR_TO_SYMBOL = {
    'BTC/USD': 'XBTUSD',
    'BTC/USDT': 'BTCUSDT',
    'ETH/USD': 'ETHUSD',
    'ETH/USDT': 'ETHUSDT'
}

const CREATE_LIMIT_ORDER = 'createLimitOrder'
const CREATE_MARKET_ORDER = 'createMarketOrder'

const SHOLO_STRATEGY = 'SHOLO_V3'
const SHOLO_STRATEGY_LIMIT = 'SHOLO_LIMIT_V3'

const ALLOWED_STRATEGIES = [SHOLO_STRATEGY, SHOLO_STRATEGY_LIMIT]

const BIDS = 'bids'
const ASKS = 'asks'
module.exports = {
    FEES,
    CANDLE_POSITIONS,
    ALLOWED_EXCHANGES,
    BITMEX_EXCHANGE,
    BINANCE_EXCHANGE,
    POSITION_LONG,
    POSITION_SHORT,
    ALLOWED_TIME_FRAMES,
    ALLOWED_ACCOUNT_TYPES,
    DEFAULT_MARKET_THRESHOLD,
    MAP_WS_PAIR_TO_SYMBOL,
    BITMEX_SYMBOLS,
    OTHER_SYMBOLS,
    CREATE_LIMIT_ORDER,
    CREATE_MARKET_ORDER,
    ALLOWED_STRATEGIES,
    SHOLO_STRATEGY,
    SHOLO_STRATEGY_LIMIT,
    BUY,
    SELL,
    BITMEX_FEE_CUTOFF,
    BTC,
    LIMIT_FEES,
    MARKET_FEES,
    BIDS,
    ASKS,
    MARGIN_TYPE_CROSS,
    MARGIN_TYPE_ISOLATED,
    ALLOWED_MARGIN_TYPES,
    ORDER_TYPE_LIMIT,
    ORDER_TYPE_MARKET
}
